# -*- coding: utf-8 -*-
"""Income_Level_Classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_uXRmNQ5DmwkETwggaw3OkCyOL1W5ztz
"""

!pip install streamlit

import streamlit as st
import numpy as np
import pickle

# Load the trained model
with open('/content/My_Model (2).pkl', 'rb') as model_file:
    model = pickle.load(model_file)

# Define the Streamlit UI
st.title("Income Level Classification App")
st.write("Predict whether a person's income is more or less than $50K based on their features.")

# Input fields
age = st.number_input("Age", min_value=18, max_value=100, value=30)
education_num = st.slider("Years of Education", min_value=1, max_value=16, value=10)
occupation = st.selectbox("Occupation", ["Tech", "Sales", "Exec", "Clerical", "Service","Other"])
hours_per_week = st.slider("Hours Worked Per Week", min_value=1, max_value=80, value=40)

# Encode categorical input
occupation_dict = {"Tech": 1, "Sales": 2, "Exec": 3, "Clerical": 4, "Service": 5, "Other": 6}
occupation_encoded = occupation_dict[occupation]

# Predict button
if st.button("Predict Income Level"):
    input_data = np.array([[age, education_num, occupation_encoded, hours_per_week]])
    prediction = model.predict(input_data)

    if prediction[0] == 0:
        st.success("Predicted Income: ≤50K")
    else:
        st.success("Predicted Income: >50K")

# Run the app with: streamlit run app.py